### ISSUE TITLE
[Bug Report] AttributeError: module 'jax.numpy' has no attribute 'DeviceArray'

### ISSUE THREAD

**Issue by SJ9VRF** [luchris429/popjaxrl#1]
### Describe the bug
Running this script `python3 run_popgym.py --num-runs 1 --env BattleshipEasy --arch s5 ` will result in error:

```
Traceback (most recent call last):
  File "*/popjaxrl-main/run_popgym.py", line 7, in <module>
    from algorithms.ppo_s5 import make_train as make_train_s5
  File "*/popjaxrl-main/algorithms/ppo_s5.py", line 12, in <module>
    from .s5 import init_S5SSM, make_DPLR_HiPPO, StackedEncoderModel
  File "*/popjaxrl-main/algorithms/s5.py", line 300, in <module>
    class S5SSM(nn.Module):
  File "*/popjaxrl-main/algorithms/s5.py", line 301, in S5SSM
    Lambda_re_init: np.DeviceArray
  File "*/anaconda3/envs/project/lib/python3.10/site-packages/jax/_src/deprecations.py", line 53, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax.numpy' has no attribute 'DeviceArray'
```

### System info

OS: macOS Sonoma 14.1.1

`pip show`
Name: jax
Version: 0.4.20
Summary: Differentiate, compile, and transform Numpy code.
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Location: */anaconda3/envs/project/lib/python3.10/site-packages
Requires: ml-dtypes, numpy, opt-einsum, scipy
Required-by: chex, distrax, flax, gymnax, optax, orbax-checkpoint

Name: jaxlib
Version: 0.4.20
Summary: XLA library for JAX
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Location: */anaconda3/envs/project/lib/python3.10/site-packages
Requires: ml-dtypes, numpy, scipy
Required-by: chex, distrax, gymnax, optax, orbax-checkpoint

Name: flax
Version: 0.7.5
Summary: Flax: A neural network library for JAX designed for flexibility
Home-page: 
Author: 
Author-email: Flax team <flax-dev@google.com>
License: 
Location: */anaconda3/envs/project/lib/python3.10/site-packages
Requires: jax, msgpack, numpy, optax, orbax-checkpoint, PyYAML, rich, tensorstore, typing-extensions
Required-by: gymnax, whisper-jax

**Comment by SJ9VRF** [comment]
cc @luchris429

**Comment by luchris429** [comment]
I'll take a closer look tomorrow. Have you tried this?

https://github.com/huggingface/transformers/issues/25417#issuecomment-1673843081

**Comment by SJ9VRF** [comment]
> I'll take a closer look tomorrow. Have you tried this? (JAX 0.4.13)
> 
> [huggingface/transformers#25417 (comment)](https://github.com/huggingface/transformers/issues/25417#issuecomment-1673843081)

Yes, I tried this one. I also attempted using JAX and JAXlib for all versions from 13 to 20, but I'm still encountering the same error. 😢

**Comment by SJ9VRF** [comment]
It can be easily resolved if you provide me with the system information and library version from the successful run. @luchris429
