### ISSUE TITLE
Paper Code Request

### ISSUE THREAD

**Issue by SeeYaaa** [luchris429/popjaxrl#4]
There is a 64 TPU Table result in the paper. 
Could you please provide also the parallel tpu/gpu training code?!

**Comment by luchris429** [comment]
Unfortunately that code is from an internship at DeepMind, so I no longer have access to it. 

That code would be quite difficult to reproduce externally, as I'm unaware of any performant re-implementations of their Muesli algorithm, and I would not have the compute to confirm that it works.

**Comment by SeeYaaa** [comment]
Is it possible to run this with pmap on multiple GPUs?
