### ISSUE TITLE
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

### ISSUE THREAD

**Issue by SeeYaaa** [luchris429/popjaxrl#5]
Hi,
i run this code on google colab with this command.
        ` python run_popgym.py --num-runs 1 --env StatelessCartPoleEasy `
The TPU/GPU was turned on.
I get this message: 
         `No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)`
Could you help me please how to run it on GPU/TPU?

**Comment by luchris429** [comment]
Yep! Do you have JAX installed for GPU? You can follow the install instructions here for that:

[https://github.com/google/jax](https://github.com/google/jax)

**Comment by SeeYaaa** [comment]
i tried this code from that link
`pip install -U "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

this installs following jax and jaxlib versions:
`jax==0.4.23
jaxlib==0.4.23+cuda12.cudnn89`

and i get this error:
`  File "/workspace/popjaxrl/run_popgym.py", line 7, in <module>
    from algorithms.ppo_s5 import make_train as make_train_s5
  File "/workspace/popjaxrl/algorithms/ppo_s5.py", line 12, in <module>
    from .s5 import init_S5SSM, make_DPLR_HiPPO, StackedEncoderModel
  File "/workspace/popjaxrl/algorithms/s5.py", line 300, in <module>
    class S5SSM(nn.Module):
  File "/workspace/popjaxrl/algorithms/s5.py", line 301, in S5SSM
    Lambda_re_init: np.DeviceArray
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/deprecations.py", line 53, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax.numpy' has no attribute 'DeviceArray'`

**Comment by SeeYaaa** [comment]
My bad i had to use your readme code.
`pip install "jax[cuda12_pip]==0.4.7" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`
Now it is working.
