### ISSUE TITLE
[Question] JAXPopGym as standalone library

### ISSUE THREAD

**Issue by EdanToledo** [luchris429/popjaxrl#7]
Hi Chris,

I was wondering if you've considered making the JAX version of PopGym a standalone JAX library that is pip installable? I feel like this would be really cool to allow people to more easily test their memory based systems (and consequently use in their libraries...😊 ). I wouldn't mind assisting with the setting up of the repo. Let me know what you think.

**Comment by luchris429** [comment]
Hi Edan,

That's a good idea! I'm a bit slammed right now with work, but would be great to have a pip installable version. I was thinking of just submitting a PR for integrating it into Gymnax, but never got around to it. What are your thoughts on how to proceed?

**Comment by EdanToledo** [comment]
A PR into gymnax would be great although I'm not sure how maintained it is and it might prevent the actual merge. A super lightweight standalone repo would be nice as well i think. I've currently made a fork of this repo and cleaned it up to make it pip installable here https://github.com/EdanToledo/popjym. I'm more than willing to simply transfer this repo to your account or whoever and then they could make a release. I think a merge into this repo would defeat the point of having a nice place for your paper to point to so a separate repo might be the best idea.

**Comment by luchris429** [comment]
Sorry for getting back to you so late on this! Would it be possible to transfer it to [FLAIROx](https://github.com/orgs/FLAIROx/repositories)? We can then put it on pypi for a release!

**Comment by luchris429** [comment]
Thanks so much for helping!

**Comment by EdanToledo** [comment]
Of course! I am technically unable to due to not having permissions to create public repos on flairox. I think it might be easier for you to clone it and then push it to a new remote (which would be a blank flairox repo)

**Comment by luchris429** [comment]
Added here! Thanks so much for the help. 

[https://github.com/FLAIROx/popjym](https://github.com/FLAIROx/popjym)

Please let me know if you want me to make any changes or updates! Also, will look into adding to pypi.

**Comment by EdanToledo** [comment]
Awesome, the link doesn't seem to work yet for me (not sure if its private). There is no immediate changes i would like to make but keen to perhaps do some work on this in the future.

**Comment by luchris429** [comment]
ah sorry my bad -- it's public now

**Comment by EdanToledo** [comment]
Thanks so much! excited to see the release!
